import React from 'react';

/* eslint-disable */
import {
  Arrow,
  Avatar,
  Badge,
  Banner,
  Block,
  Blockquote,
  Breadcrumbs,
  Button,
  ButtonCircle,
  ButtonOutline,
  Card,
  CardImage,
  Checkbox,
  Close,
  Container,
  Divider,
  Donut,
  DotIndicator,
  Drawer,
  Dropdown,
  DropdownMenu,
  Embed,
  Fixed,
  Footer,
  Heading,
  HeadingLink,
  InlineForm,
  Input,
  Label,
  LinkBlock,
  Media,
  Menu,
  Message,
  NavItem,
  Overlay,
  PageHeader,
  Panel,
  PanelFooter,
  PanelHeader,
  Pre,
  Progress,
  Radio,
  Rating,
  Section,
  SectionHeader,
  Select,
  SequenceMap,
  SequenceMapStep,
  Slider,
  Space,
  Stat,
  Switch,
  Table,
  Text,
  Textarea,
  Toolbar,
  Tooltip,
} from 'rebass';
/* eslint-enable */

export const rebassComponents = [
  { children: 'Arrow', component: React.createElement(Arrow, null, null), },
  { children: 'Avatar', component: React.createElement(Avatar, null, null), },
  { children: 'Badge', component: React.createElement(Badge, null, null), },
  { children: 'Banner', component: React.createElement(Banner, null, null), },
  { children: 'Block', component: React.createElement(Block, null, null), },
  { children: 'Blockquote', component: React.createElement(Blockquote, null, null), },
  { children: 'Breadcrumbs', component: React.createElement(Breadcrumbs, null, null), },
  { children: 'Button', component: React.createElement(Button, null, null), },
  { children: 'ButtonCircle', component: React.createElement(ButtonCircle, null, null), },
  { children: 'ButtonOutline', component: React.createElement(ButtonOutline, null, null), },
  { children: 'Card', component: React.createElement(Card, null, null), },
  { children: 'CardImage', component: React.createElement(CardImage, null, null), },
  { children: 'Checkbox', component: React.createElement(Checkbox, null, null), },
  { children: 'Close', component: React.createElement(Close, null, null), },
  { children: 'Container', component: React.createElement(Container, null, null), },
  { children: 'Divider', component: React.createElement(Divider, null, null), },
  { children: 'Donut', component: React.createElement(Donut, null, null), },
  { children: 'DotIndicator', component: React.createElement(DotIndicator, null, null), },
  { children: 'Drawer', component: React.createElement(Drawer, null, null), },
  { children: 'Dropdown', component: React.createElement(Dropdown, null, null), },
  { children: 'DropdownMenu', component: React.createElement(DropdownMenu, null, null), },
  { children: 'Embed', component: React.createElement(Embed, null, null), },
  { children: 'Fixed', component: React.createElement(Fixed, null, null), },
  { children: 'Footer', component: React.createElement(Footer, null, null), },
  { children: 'Heading', component: React.createElement(Heading, null, null), },
  { children: 'HeadingLink', component: React.createElement(HeadingLink, null, null), },
  { children: 'InlineForm', component: React.createElement(InlineForm, null, null), },
  { children: 'Input', component: React.createElement(Input, null, null), },
  { children: 'Label', component: React.createElement(Label, null, null), },
  { children: 'LinkBlock', component: React.createElement(LinkBlock, null, null), },
  { children: 'Media', component: React.createElement(Media, null, null), },
  { children: 'Menu', component: React.createElement(Menu, null, null), },
  { children: 'Message', component: React.createElement(Message, null, null), },
  { children: 'NavItem', component: React.createElement(NavItem, null, null), },
  { children: 'Overlay', component: React.createElement(Overlay, null, null), },
  { children: 'PageHeader', component: React.createElement(PageHeader, null, null), },
  { children: 'Panel', component: React.createElement(Panel, null, null), },
  { children: 'PanelFooter', component: React.createElement(PanelFooter, null, null), },
  { children: 'PanelHeader', component: React.createElement(PanelHeader, null, null), },
  { children: 'Pre', component: React.createElement(Pre, null, null), },
  { children: 'Progress', component: React.createElement(Progress, null, null), },
  { children: 'Radio', component: React.createElement(Radio, null, null), },
  { children: 'Rating', component: React.createElement(Rating, null, null), },
  { children: 'Section', component: React.createElement(Section, null, null), },
  { children: 'SectionHeader', component: React.createElement(SectionHeader, null, null), },
  { children: 'Select', component: React.createElement(Select, null, null), },
  { children: 'SequenceMap', component: React.createElement(SequenceMap, null, null), },
  { children: 'SequenceMapStep', component: React.createElement(SequenceMapStep, null, null), },
  { children: 'Slider', component: React.createElement(Slider, null, null), },
  { children: 'Space', component: React.createElement(Space, null, null), },
  { children: 'Stat', component: React.createElement(Stat, null, null), },
  { children: 'Switch', component: React.createElement(Switch, null, null), },
  { children: 'Table', component: React.createElement(Table, null, null), },
  { children: 'Text', component: React.createElement(Text, null, null), },
  { children: 'Textarea', component: React.createElement(Textarea, null, null), },
  { children: 'Toolbar', component: React.createElement(Toolbar, null, null), },
  { children: 'Tooltip', component: React.createElement(Tooltip, null, null), },
];
